title: ROSS
email: rossug@cs.lists.rpi.edu
description: "Rensselaer's Optimistic Simulation System"
github_username: carothersc

safe:        true
baseurl:

source:      .
markdown_ext:  markdown,mkdown,mkdn,mkd,md
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
highlighter: rouge
markdown:    redcarpet
permalink:   none

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  
  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style
