title: ROSS
email: rossug@cs.lists.rpi.edu
description: "Rensselaer's Optimistic Simulation System"
github_username: carothersc

safe:    true
baseurl: /ROSS

source:      .
markdown_ext:  markdown,mkdown,mkdn,mkd,md
destination: ./_site
plugins_dir:     ./_plugins

exclude: [CONTRIBUTING.md, README.md, _drafts/README.md]

future:      true
lsi:         false
highlighter: rouge
markdown:    kramdown
permalink:   none

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  parse_block_html: true
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style
