title: ROSS
email: rossug@cs.lists.rpi.edu
description: "Rensselaer's Optimistic Simulation System"
github_username: carothersc

safe:    true
baseurl: /ROSS

source:      .
markdown_ext:  markdown,mkdown,mkdn,mkd,md
destination: ./_site
plugins_dir:     ./_plugins

exclude: [CONTRIBUTING.md, README.md, _drafts/README.md]

future:      true
lsi:         false
highlighter: rouge
markdown:    kramdown
permalink:   none

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  parse_block_html: true
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
